find_smallest_cycle: don't drop children via ignore_priority (bug 756199)
Fix find_smallest_cycle to stop using the ignore_priority parameter
for gather_deps, since that caused it to drop children that should
have been selected. Instead, gradually increase the ignore_priority
used to populate the mergeable_nodes set that is passed to
find_smallest_cycle. Also, order the mergeable_nodes by increasing
edge priority, in order to prefer cycles with lower priority edges.
This changes a MergeOrderTestCase result to that one cycle with
lower priority edges is merged earlier.

FIXME with some gather_deps code *uncommented*:

======================================================================
FAIL: testMergeOrder (portage.tests.resolver.test_merge_order.MergeOrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lib/portage/tests/__init__.py", line 248, in run
    testMethod()
  File "lib/portage/tests/resolver/test_merge_order.py", line 719, in testMergeOrder
    self.assertEqual(test_case.test_success, True, test_case.fail_msg)
AssertionError: False != True : atoms: (app-misc/circ-buildtime-unsolvable-a), key: success, expected: False, got: True
atoms: (app-misc/circ-buildtime-unsolvable-a), key: mergelist, expected: None, got: ['app-misc/circ-buildtime-unsolvable-b-1', 'app-misc/circ-buildtime-unsolvable-a-1', 'app-misc/circ-buildtime-unsolvable-c-1']
atoms: (app-misc/circ-buildtime-unsolvable-a), key: circular_dependency_solutions, expected: {}, got: None

------------------------------------------------------------------

FIXME with some gather_deps code *commented*:

======================================================================
FAIL: testRuntimeCycleMergeOrder (portage.tests.resolver.test_runtime_cycle_merge_order.RuntimeCycleMergeOrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lib/portage/tests/__init__.py", line 248, in run
    testMethod()
  File "lib/portage/tests/resolver/test_runtime_cycle_merge_order.py", line 71, in testRuntimeCycleMergeOrder
    self.assertEqual(test_case.test_success, True, test_case.fail_msg)
AssertionError: False != True : atoms: (app-misc/plugin-b), key: success, expected: True, got: False
atoms: (app-misc/plugin-b), key: mergelist, expected: [{'app-misc/leaf-e-1', 'app-misc/leaf-d-1', 'app-misc/leaf-b-1'}, {'app-misc/branch-e-1', 'app-misc/branch-d-1'}, 'app-misc/runtime-c-1', {'app-misc/runtime-cycle-c-1', 'app-misc/branch-c-1'}, 'app-misc/branch-b-1', {'app-misc/runtime-cycle-b-1', 'app-misc/plugin-b-1'}, 'app-misc/plugins-consumer-1'], got: None
atoms: (app-misc/plugin-b), key: circular_dependency_solutions, expected: None, got: {}

----------------------------------------------------------------------

Bug: https://bugs.gentoo.org/756199
Signed-off-by: Zac Medico <zmedico@gentoo.org>