bug 645914 WIP
This currently breaks the following test:

FAIL: testResolverDepth (portage.tests.resolver.test_depth.ResolverDepthTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pym/portage/tests/__init__.py", line 222, in run
    testMethod()
  File "pym/portage/tests/resolver/test_depth.py", line 250, in testResolverDepth
    self.assertEqual(test_case.test_success, True, test_case.fail_msg)
AssertionError: False != True : atoms: (virtual/jre), key: mergelist, expected: ['virtual/jdk-1.6.0-r1', 'virtual/jdk-1.5.0-r1', 'virtual/jre-1.6.0-r1', 'virtual/jre-1.5.0-r1', ('dev-java/icedtea-6.1-r1', 'dev-java/gcj-jdk-4.5-r1')], got: ['virtual/jdk-1.6.0-r1', 'virtual/jdk-1.5.0-r1', 'virtual/jre-1.6.0-r1', 'virtual/jre-1.5.0-r1']

Bug: https://bugs.gentoo.org/645914